from flask import Flask, jsonify

app = Flask(__name__)

# Fallo intencional para Bandit
MYSQL_PASSWORD = "super_secret_123"

@app.route('/')
def home():
    return jsonify({"message": "API activa"})

if __name__ == '__main__':
    # Fallo intencional: debug=True
    app.run(host='0.0.0.0', port=5000, debug=True)